apiVersion: v1
kind: Namespace
metadata:
    name: mi-namespace

---

apiVersion: v1
kind: LimitRange
metadata:
    name: limitacion-cpu
    namespace: mi-namespace
spec:
    limits:
        - default:
            cpu: "500m" 
          defaultRequest:
            cpu: "400m"
          max:
            cpu: "600m"
          min:
            cpu: "200m"
          type: Container
# Si un desarrollador no pone nada: 
    # limit:   500
    # request: 400
# Si un desarrollador si pone algo 
    # limit:   lo que él ponga pero nunca por encima de 600
    # request: lo que él ponga pero nunca por encima de 600


---

apiVersion: v1
kind: ResourceQuota
metadata:
    name: limitacion-pods
    namespace: mi-namespace
spec:
    hard:
        pods: 2