apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-peticion-volumen-nfs
spec:
    storageClassName: nfs-client
    resources: 
      requests:
        storage: 20Mi
    accessModes:
      - ReadWriteOnce
