apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "800Mi"
            cpu: "200m" #<1 milicore: Puede usar un 20% de un core
          requests:              ###### SCHEDULLER
            memory: "800Mi"
            cpu: "100m" #<1 milicore: Puede usar un 20% de un core
